local window=require("tools.window")
local monarch = require "monarch.monarch"
local defsave = require("defsave.defsave")


function init(self)
	
	msg.post("#", "init_monarch")	
	msg.post(".","acquire_input_focus")	

	window.center()
	window.resize()
	
	msg.post(".", "acquire_input_focus")
end

function on_message(self, message_id, message, sender)
	if message_id == hash("init_monarch") then		
		monarch.show(hash("start_screen"))
	end
end

function on_input(self, action_id, action)
	
end